---
name: Backup Application Files

on:
  workflow_call:

env:
  BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  OBJECT: ${{ secrets.AWS_S3_OBJECT }}
  RETAIN_BACKUPS: ${{ secrets.FILE_BACKUP_RETAIN }}
  APPLICATION_PATH: ${{ secrets.FILE_BACKUP_APPLICATION_PATH }}

jobs:
  backup:
    name: Backup Files
    runs-on: ubuntu-22.04
    container: python:3.8
    steps:
      - name: Set runtime variables
        id: vars
        run: |
          echo "timestamp=$(date -d@"$(( \
          $(date +%s) + (5 * 3600) + (30 * 60) ))" \
          +'%d-%m-%Y-%H%M')" >> "$GITHUB_ENV"

      - name: Install system packages
        run: |
          apt-get update --assume-yes
          apt-get install rsync --assume-yes

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Manually Set SSH key
        if: ${{ env.ACT }}
        run: |
          mkdir --parents ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SERVER_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.8.0
        if: ${{ !env.ACT }}
        with:
          ssh-private-key: ${{ secrets.SERVER_SECRET_KEY }}

      - name: Compress application files
        uses: appleboy/ssh-action@v0.1.10
        env:
          TIMESTAMP: ${{ env.timestamp }}
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SECRET_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: APPLICATION_PATH, TIMESTAMP
          script: |
            export APPLICATION_PATH=$APPLICATION_PATH
            mkdir --parent /srv/rsync/backups
            cd $APPLICATION_PATH && zip --recurse-paths /srv/rsync/backups/$TIMESTAMP-files.zip .

      - name: Transport files
        env:
          TIMESTAMP: ${{ env.timestamp }}
        run: >
          mkdir --parents /srv/rsync/backups && rsync
          --archive
          --verbose
          --compress
          --delete
          --remove-source-files
          --rsh "ssh -o StrictHostKeyChecking=no"
          ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }}:/srv/rsync/backups/$TIMESTAMP-files.zip
          /srv/rsync/backups/${{ env.timestamp }}-files.zip

      - name: Configure AWS credentials
        run: |
          mkdir --parents ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Upload backup to S3 bucket
        run: >
          aws s3 cp 
          /srv/rsync/backups/${{ env.timestamp }}-files.zip 
          s3://$BUCKET/$OBJECT/${{ env.timestamp }}-files.zip 
          --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }}

      - name: Delete excess backups in S3 bucket
        run: >
          counter=0

          files=$(aws s3api list-objects \
            --bucket "$BUCKET" \
            --prefix "$OBJECT/" \
            --query 'Contents[?ends_with(Key, `'-files.zip'`)].[Key, LastModified]' \
            --output text \
            --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }} \
            | sort -k2 -r \
            | awk '{print $1}' \
          )

          for file in $files; do
              counter=$((counter + 1))
              if [ $counter -le $RETAIN_BACKUPS ]; then
                continue
              fi
              aws s3 rm s3://$BUCKET/$file --endpoint-url ${{ secrets.AWS_S3_ENDPOINT }};
          done

      - name: Discord success notification
        uses: Ilshidur/action-discord@master
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🟢 Files backup completed at: ${{ env.timestamp }}."

      - name: Discord failure notification
        uses: Ilshidur/action-discord@master
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🛑 Files backup failed at: ${{ env.timestamp }}."
